# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 600)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEditTraffic = QtWidgets.QTextEdit(Dialog)
        self.textEditTraffic.setObjectName("textEditTraffic")
        self.verticalLayout_2.addWidget(self.textEditTraffic)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditData = LineEdit(Dialog)
        self.lineEditData.setObjectName("lineEditData")
        self.horizontalLayout.addWidget(self.lineEditData)
        self.pushButtonSend = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSend.setFont(font)
        self.pushButtonSend.setAutoDefault(False)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.horizontalLayout.addWidget(self.pushButtonSend)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 17, 1)
        self.labelDevice = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDevice.setFont(font)
        self.labelDevice.setObjectName("labelDevice")
        self.gridLayout.addWidget(self.labelDevice, 0, 1, 1, 1)
        self.lineEditDevice = QtWidgets.QLineEdit(Dialog)
        self.lineEditDevice.setMinimumSize(QtCore.QSize(160, 0))
        self.lineEditDevice.setMaximumSize(QtCore.QSize(160, 16777215))
        self.lineEditDevice.setObjectName("lineEditDevice")
        self.gridLayout.addWidget(self.lineEditDevice, 1, 1, 1, 1)
        self.labelBaudRate = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelBaudRate.setFont(font)
        self.labelBaudRate.setObjectName("labelBaudRate")
        self.gridLayout.addWidget(self.labelBaudRate, 2, 1, 1, 1)
        self.comboBoxBaudRate = QtWidgets.QComboBox(Dialog)
        self.comboBoxBaudRate.setObjectName("comboBoxBaudRate")
        self.gridLayout.addWidget(self.comboBoxBaudRate, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 15, 1, 1, 1)
        self.labelDataBits = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDataBits.setFont(font)
        self.labelDataBits.setObjectName("labelDataBits")
        self.gridLayout.addWidget(self.labelDataBits, 4, 1, 1, 1)
        self.comboBoxDataBits = QtWidgets.QComboBox(Dialog)
        self.comboBoxDataBits.setObjectName("comboBoxDataBits")
        self.comboBoxDataBits.addItem("")
        self.comboBoxDataBits.addItem("")
        self.comboBoxDataBits.addItem("")
        self.comboBoxDataBits.addItem("")
        self.gridLayout.addWidget(self.comboBoxDataBits, 5, 1, 1, 1)
        self.labelParity = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelParity.setFont(font)
        self.labelParity.setObjectName("labelParity")
        self.gridLayout.addWidget(self.labelParity, 6, 1, 1, 1)
        self.comboBoxParity = QtWidgets.QComboBox(Dialog)
        self.comboBoxParity.setObjectName("comboBoxParity")
        self.comboBoxParity.addItem("")
        self.comboBoxParity.addItem("")
        self.comboBoxParity.addItem("")
        self.comboBoxParity.addItem("")
        self.comboBoxParity.addItem("")
        self.gridLayout.addWidget(self.comboBoxParity, 7, 1, 1, 1)
        self.labelStopBits = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelStopBits.setFont(font)
        self.labelStopBits.setObjectName("labelStopBits")
        self.gridLayout.addWidget(self.labelStopBits, 8, 1, 1, 1)
        self.comboBoxStopBits = QtWidgets.QComboBox(Dialog)
        self.comboBoxStopBits.setObjectName("comboBoxStopBits")
        self.comboBoxStopBits.addItem("")
        self.comboBoxStopBits.addItem("")
        self.comboBoxStopBits.addItem("")
        self.gridLayout.addWidget(self.comboBoxStopBits, 9, 1, 1, 1)
        self.labelFormat = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFormat.setFont(font)
        self.labelFormat.setObjectName("labelFormat")
        self.gridLayout.addWidget(self.labelFormat, 10, 1, 1, 1)
        self.comboBoxFormat = QtWidgets.QComboBox(Dialog)
        self.comboBoxFormat.setMinimumSize(QtCore.QSize(160, 0))
        self.comboBoxFormat.setMaximumSize(QtCore.QSize(160, 16777215))
        self.comboBoxFormat.setObjectName("comboBoxFormat")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.gridLayout.addWidget(self.comboBoxFormat, 11, 1, 1, 1)
        self.checkBoxLeadingZeroes = QtWidgets.QCheckBox(Dialog)
        self.checkBoxLeadingZeroes.setObjectName("checkBoxLeadingZeroes")
        self.gridLayout.addWidget(self.checkBoxLeadingZeroes, 12, 1, 1, 1)
        self.checkBoxRawText = QtWidgets.QCheckBox(Dialog)
        self.checkBoxRawText.setObjectName("checkBoxRawText")
        self.gridLayout.addWidget(self.checkBoxRawText, 13, 1, 1, 1)
        self.checkBoxTimestamp = QtWidgets.QCheckBox(Dialog)
        self.checkBoxTimestamp.setObjectName("checkBoxTimestamp")
        self.gridLayout.addWidget(self.checkBoxTimestamp, 14, 1, 1, 1)
        self.pushButtonOpenClose = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOpenClose.setFont(font)
        self.pushButtonOpenClose.setAutoDefault(False)
        self.pushButtonOpenClose.setObjectName("pushButtonOpenClose")
        self.gridLayout.addWidget(self.pushButtonOpenClose, 16, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.comboBoxFormat.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditDevice, self.lineEditData)
        Dialog.setTabOrder(self.lineEditData, self.pushButtonSend)
        Dialog.setTabOrder(self.pushButtonSend, self.comboBoxFormat)
        Dialog.setTabOrder(self.comboBoxFormat, self.checkBoxTimestamp)
        Dialog.setTabOrder(self.checkBoxTimestamp, self.textEditTraffic)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Serial debugger - 2.1.1"))
        self.pushButtonSend.setText(_translate("Dialog", "Send"))
        self.labelDevice.setText(_translate("Dialog", "Device:"))
        self.lineEditDevice.setText(_translate("Dialog", "/dev/ttyS0"))
        self.labelBaudRate.setText(_translate("Dialog", "Baud rate:"))
        self.labelDataBits.setText(_translate("Dialog", "Data bits:"))
        self.comboBoxDataBits.setItemText(0, _translate("Dialog", "5"))
        self.comboBoxDataBits.setItemText(1, _translate("Dialog", "6"))
        self.comboBoxDataBits.setItemText(2, _translate("Dialog", "7"))
        self.comboBoxDataBits.setItemText(3, _translate("Dialog", "8"))
        self.labelParity.setText(_translate("Dialog", "Parity:"))
        self.comboBoxParity.setItemText(0, _translate("Dialog", "None"))
        self.comboBoxParity.setItemText(1, _translate("Dialog", "Even"))
        self.comboBoxParity.setItemText(2, _translate("Dialog", "Odd"))
        self.comboBoxParity.setItemText(3, _translate("Dialog", "Mark"))
        self.comboBoxParity.setItemText(4, _translate("Dialog", "Space"))
        self.labelStopBits.setText(_translate("Dialog", "Stop bits:"))
        self.comboBoxStopBits.setItemText(0, _translate("Dialog", "1"))
        self.comboBoxStopBits.setItemText(1, _translate("Dialog", "1.5"))
        self.comboBoxStopBits.setItemText(2, _translate("Dialog", "2"))
        self.labelFormat.setText(_translate("Dialog", "Format:"))
        self.comboBoxFormat.setItemText(0, _translate("Dialog", "Bin"))
        self.comboBoxFormat.setItemText(1, _translate("Dialog", "Oct"))
        self.comboBoxFormat.setItemText(2, _translate("Dialog", "Dec"))
        self.comboBoxFormat.setItemText(3, _translate("Dialog", "Hex"))
        self.checkBoxLeadingZeroes.setText(_translate("Dialog", "Leading zeroes"))
        self.checkBoxRawText.setText(_translate("Dialog", "Raw text"))
        self.checkBoxTimestamp.setText(_translate("Dialog", "Timestamp"))
        self.pushButtonOpenClose.setText(_translate("Dialog", "Open"))


from debugger.widgets import LineEdit
